### ISSUE TITLE
Integration of question, matching and collaboration service

### ISSUE THREAD

**Issue by ys112** [CS3219-AY2425S1/cs3219-ay2425s1-project-g20#84]
- Upon matching, matching svc calls collab svc to create collaboration data containing room Id with users matched and get a question with the specified topic and difficulty
- Return the collaboration data to frontend
- Frontend displays question
- Frontend initiates collaboration with the room ID (need to figure out how to send users and question id across)
- 
![image](https://github.com/user-attachments/assets/3d9fdfc9-2d5f-498f-8f79-21bdf91832ba)

**Comment by Cloud7050** [comment]
There was discussion about using another shared token for communication between services, fixed in the env files. Separate from the existing user verification JWT system.

https://dotnetfullstackdev.medium.com/secure-communication-between-microservices-without-an-identity-server-product-and-order-services-69f9b36956dd#:~:text=A%20shared%20secret%20token%20is,identity%20of%20the%20calling%20service
